import type { Metadata } from "next";
import "./globals.css";
import {Montserrat} from 'next/font/google'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const montserrate = Montserrat({subsets: ['latin']})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={montserrate.className}>{children}</body>
      <footer>a</footer>
    </html>
  );
}
